export const mockUsers = [
  {
    id: 1,
    email: "student@amity.edu",
    password: "password123",
    role: "student",
    name: "John Doe",
    department: "Computer Science",
    studentId: "A12345678",
    phone: "+91 9876543210",
    avatar: "/student-avatar.png",
  },
  {
    id: 2,
    email: "faculty@amity.edu",
    password: "password123",
    role: "faculty",
    name: "Dr. Jane Smith",
    department: "Computer Science",
    employeeId: "F001",
    phone: "+91 9876543211",
    avatar: "/diverse-faculty-avatars.png",
  },
  {
    id: 3,
    email: "admin@amity.edu",
    password: "password123",
    role: "admin",
    name: "Admin User",
    department: "Administration",
    employeeId: "A001",
    phone: "+91 9876543212",
    avatar: "/admin-avatar.png",
  },
]

export const mockCertificates = [
  {
    id: "CERT001",
    studentId: 1,
    studentName: "John Doe",
    type: "Course Completion",
    courseName: "Advanced Web Development",
    issueDate: "2024-01-15",
    status: "issued",
    verificationCode: "AMT2024001",
    department: "Computer Science",
  },
  {
    id: "CERT002",
    studentId: 1,
    studentName: "John Doe",
    type: "Internship",
    courseName: "Summer Internship Program",
    issueDate: "2024-02-20",
    status: "issued",
    verificationCode: "AMT2024002",
    department: "Computer Science",
  },
]

export const mockRequests = [
  {
    id: 1,
    studentId: 1,
    studentName: "John Doe",
    type: "Course Completion",
    courseName: "Data Structures and Algorithms",
    requestDate: "2024-01-10",
    status: "pending",
    department: "Computer Science",
    comments: "",
  },
  {
    id: 2,
    studentId: 1,
    studentName: "John Doe",
    type: "Event Participation",
    courseName: "Tech Fest 2024",
    requestDate: "2024-01-12",
    status: "approved",
    department: "Computer Science",
    comments: "Approved by faculty advisor",
  },
]
